version: '3'

services:
  mysql:
    build: ./db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - bearder-net
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/mysql

  back:
    build: ./bearder_back
    ports:
      - "8080:8080"
    networks:
      - bearder-net
    depends_on:
      - mysql

  front:
    build: ./bearder_front
    ports:
      - "80:3000"
    stdin_open: true
    networks:
      - bearder-net
    volumes:
      - ./bearder_front:/front
    depends_on:
      - back
      - mysql

volumes:
  db-data:

networks:
  bearder-net:
